### ISSUE TITLE
Crystal 0.19.x compatibility

### ISSUE THREAD

**Issue by theodorton** [jeromegn/slang#11]
I'm seeing some errors when attempting to run the specs for the project with Crystal 0.19.

```
>    Error in ./src/slang.cr:3: while requiring "./slang/node"
>
>    require "./slang/node"
>    ^
>
>    in ./src/slang/node.cr:52: while requiring "./nodes/*"
>
>    require "./nodes/*"
>    ^
>
>    Syntax error in ./src/slang/nodes/element.cr:10: unexpected token: as
>
>            names = attributes.delete("class") as Set
>                                               ^
>
```

Looks like [the new syntax](https://github.com/crystal-lang/crystal/issues/2482) is `object.as(Klass)`.

**Comment by jeromegn** [comment]
Oh yes. I need to go through my Crystal projects and update them for 0.19.

Thanks for the heads up!
