### ISSUE TITLE
script / style

### ISSUE THREAD

**Issue by crisward** [jeromegn/slang#13]
How should I use style tags ? I get a compile error at the moment. 
I noticed these two tags are mentioned here https://github.com/jeromegn/slang/blob/master/src/slang/nodes/element.cr#L5 but don't seem to be used anywhere in the code.

Thanks.

**Comment by jeromegn** [comment]
Ah, good catch. Looks like I foresaw the issue, but forgot to implement it.

I'm assuming it's a quick fix, one conditional somewhere. I don't have time to get into that context right now though.

Feel free to give it a try or I'll probably come around to doing it in a little while.

**Comment by crisward** [comment]
I gave it a try, new to crystal and never wrote a template engine. Got a bit stuck. Looks like a may need to create another node type, but not sure. Any hints would be appreciated.

Thanks.

**Comment by elorest** [comment]
Any update on this?

**Comment by jeromegn** [comment]
@elorest not presently. I'm not actively using this library and have little time to work on OSS at the moment.

Although not necessary for this specific issue: I'd like to rewrite this library using a parser/lexer generator (like https://github.com/ziprandom/cltk), if I can find a good one.

In any case, if anybody wants to try and fix this issue, they are welcome to do so.

@crisward do you remember what error you got? @elorest have you gotten a compile error as well? If so, which one?

**Comment by elorest** [comment]
I'm compiling ok. I'll look into compiling fixing this.

**Comment by elorest** [comment]
This fixes it. https://github.com/jeromegn/slang/pull/17

**Comment by crisward** [comment]
@elorest Thanks for your help with this, good work!

**Comment by jeromegn** [comment]
That is indeed now fixed, thanks to @elorest.

Available in v1.5.0
