### ISSUE TITLE
multiline javascript strings using backtick do not compile

### ISSUE THREAD

**Issue by fridgerator** [jeromegn/slang#24]
reported also in kilt https://github.com/jeromegn/kilt/issues/14

For instance, when using Vue inline:

```javascript
script src="https://cdnjs.cloudflare.com/ajax/libs/vue/2.3.4/vue.min.js"

#app

javascript:
  new Vue({
    el: '#app',
    template: `
      <div>
        something
      </div>
    `
  })
```

It seems like the `run` macro raises the exception: `unterminated parenthesized expression`

**Comment by jeromegn** [comment]
@fridgerator I just pushed slang changes with this test case in there and it passes, I'm not sure what's up.

Mind testing it out with slang 42263ba0e1e3a3fbada0e880575d59243e29be51 to see if you can replicate the issue?

**Comment by jeromegn** [comment]
Latest release contains the changes, v1.7.0
