### ISSUE TITLE
optional end keyword

### ISSUE THREAD

**Issue by faustinoaq** [jeromegn/slang#31]
Hi @jeromegn 

I like slang a lot, however sometimes I would like to see an `end` keyword, [for some reasons](https://github.com/crystal-lang/crystal/wiki/FAQ#why-isnt-the-language-indentation-based)

`end` keyword give some kind of structure to logic code, I know slang is slim compatible, but Do you think would be possible to add optional `- end` line inside slang templates? I mean:

Before: (looks good for tags, but I miss `end` keyword on blocks and statements)

It feels more like Python 🐍 

```slim
- if user = session["user"]
  p You are
    span.user
      = user
    a.btn.btn-danger.btn-xs href="/logout"
      | Logout
  div#messages
  == form do
    == text_field(name: "message", placeholder: "Your message here")
- else
  == form do
    == csrf_tag
    == text_field(name: "user", placeholder: "Your name here")
```

After (using `end` keyword) 🎉 

Now It feels more like ruby/crystal 💎 

```slim
- if user = session["user"]
  p You are
    span.user
      = user
    a.btn.btn-danger.btn-xs href="/logout"
      | Logout
  div#messages
  == form do
    == text_field(name: "message", placeholder: "Your message here")
  - end
- else
  == form do
    == csrf_tag
    == text_field(name: "user", placeholder: "Your name here")
  - end
- end
```

Currently my templates looks like:

```slim
- if user = session["user"]
  p You are
    span.user
      = user
    a.btn.btn-danger.btn-xs href="/logout"
      | Logout
  div#messages
  == form(class: "form-group", id: "form-message") do
    == text_field(name: "message", autofocus: "", required: "", class: "form-control", id: "message", placeholder: "Your message here")
  - :end
- else
  == form(class: "form-group") do
    == csrf_tag
    == text_field(name: "user", autofocus: "", required: "", class: "form-control", placeholder: "Your name here")
  - :end
- :end
```

Just for blocks and statements, WDYT? 🤔

**Comment by jeromegn** [comment]
Crystal isn't indentation based, but slang is.

I could probably just ignore any `- end`, but that doesn't seem very useful :(

**Comment by faustinoaq** [comment]
I understand, Thank for you response! 👍
