### ISSUE TITLE
SecureRandom is not used anymore in Crystal 0.24.x

### ISSUE THREAD

**Issue by Wulfklaue** [jeromegn/slang#33]
Crystal 24.1 does not have SecureRandom anymore.

https://github.com/crystal-lang/crystal/commit/27684db49083bfd95f27a90321cf7c0817929f8e#diff-4c5f0c441b8e7feb9e3dcc106919870c

Please use:

/slang/src/slang/nodes/text.cr
```
01: require "random/secure"
22: sub_buffer_name = "#{buffer_name}#{Random::Secure.hex(8)}"
```

**Comment by veelenga** [comment]
You need to use master for now. See #28

**Comment by Wulfklaue** [comment]
No problem, already adjusted the code locally :)
