### ISSUE TITLE
slang with strings?

### ISSUE THREAD

**Issue by Wulfklaue** [jeromegn/slang#35]
Slang works perfectly with files ( embed ) but the program will also use strings as to embed the slang information into the compiled executable.

My attempt at bypassing Slang its file requirement, is to run Slang.process_string but the whole buffer and other symbols are also output.

There are ways around it by temporary creating a file, writing the string value and then letting slang read it but that is silly and will have performance issues.

If there a way to force slang to run processes with string, without the whole buffer output?

**Comment by Wulfklaue** [comment]
Never mind ... solve the issue.

**Comment by jeromegn** [comment]
Oh nice, should I update the README for clearer examples on doing this?
