### ISSUE TITLE
Use of conditionals

### ISSUE THREAD

**Issue by renich** [jeromegn/slang#57]
I've been trying to use conditionals but haven't found a way to do it.

**Comment by renich** [comment]
Found out the spec file: /spec/fixtures/if-elsif-else.slang

Maybe just add it to the example in the README?

**Comment by jeromegn** [comment]
I'm only passively maintaining this shard. Happy to merge a PR if you submit one :)

**Comment by renich** [comment]
OK. I'll send something.
