### ISSUE TITLE
Colons in attributes not working.

### ISSUE THREAD

**Issue by crisward** [jeromegn/slang#8]
When linking SVG, it uses odd attributes with colons in. 
The template engine seems to be closing the tag, then escaping these.

eg.

```slim
svg width="256" height="448" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" 
```
converts to 
```html
<svg width="256" height="448" xmlns="http://www.w3.org/2000/svg">xmlns:xlink&#61;&quot;http://www.w3.org/1999/xlink&quot;
```

**Comment by jeromegn** [comment]
Thanks for reporting this. Should be a fairly simple fix. Need to find the time to implement it though!

**Comment by crisward** [comment]
chucked a fix your way... hopefully ok
